import './globals.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';
import Navabar from '@/components/navbar';
import Sidebar from '@/components/sidebar/sidebar';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
   <html lang="en">
      <body className="w-screen h-screen overflow-x-auto ">
        <div className="whitespace-nowrap flex flex-col min-h-screen ">
       <Navabar/>
          <Sidebar/>
          <main className="p-6 inline-block align-top">{children}</main>
        </div>
      </body>
    </html>
  );
}
