import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
export const metadata = {
  title: "Job portal",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="w-full h-screen overflow-x-auto">
        <div id="backdrop"></div>
        <div id="overlay"></div>
        <div>
          {children}
          <ToastContainer position="top-center" autoClose={2000} />
        </div>
      </body>
    </html>
  );
}
